
version: "3.7"

services:
  directus95b506d-redis:
    image: redis:7.2.4
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]
    volumes:
      - directus95b506d-redis-data:/data
    networks: 
      - interna
    deploy:
      placement:
        constraints:
          - node.role == manager
     # resources:
      #  limits:
        #  cpus: "0.5"
        #  memory: 1024M

volumes:
  directus95b506d-redis-data:
    external: true
    name: directus95b506d-redis-data

networks: 
  interna: 
    external: true


