
version: "3.7"
services:

  krayincrm321a1a2:
    image: francisbreit/crmk:v2.0.5-fr

    volumes:
      - krayincrm321a1a2-data:/var/www/html

    networks: 
      - externa
      - interna
      
    environment:
      ## Dados de acesso
      - APP_NAME=Domuss
      - APP_URL=https://crm.domussimob.com.br
      - APP_ENV=production
      - APP_KEY=base64:ahHFFU8JfZpAiI0tEc+Rj2qINvA9sN6PMRDckLvICWY=
      - APP_DEBUG=false
      - APP_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - APP_LOCALE=pt_BR
      - APP_CURRENCY=BRL
      - SWAGGER_SERVER_URL=https://crm.domussimob.com.br
      - L5_SWAGGER_UI_PERSIST_AUTHORIZATION=true

      - SANCTUM_STATEFUL_DOMAINS=https://crm.domussimob.com.br 
      - SESSION_DOMAIN=crm.domussimob.com.br
      #- LOG_CHANNEL=stack
      #- LOG_LEVEL=debug
      - krayin_PUBLIC_URL=https://crm.domussimob.com.br
      #- krayin_CADDY_ADDRESSES=:80

      ## Configuração do Banco de Dados
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=krayincrm321a1a2
      - DB_USERNAME=root
      - DB_PASSWORD=1e46ea0d3bf4ad47
      - DB_PREFIX=

      ## Configurações de e-mail
      - MAIL_MAILER=smtp
      - MAIL_FROM_ADDRESS=contato@dominio.com ## mude
      - MAIL_USERNAME=contato@dominio.com ## mude
      - MAIL_PASSWORD=Kgdgd6jkm ## mude
      - MAIL_HOST=smtp.site.com ## mude
      - MAIL_PORT=465 ## mude
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_NAME="Domuss" ## mude
      #- MAIL_DOMAIN=DOMINIO_SMTP # ALTERAR_SE_PRECISAR_DO_E_MAIL <<<<<<<<<<

      ## Configurações de Cache e Sessão
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120

      ## Configurações de Redis
      - REDIS_HOST=redis
      #- REDIS_PASSWORD=null
      - REDIS_PORT=6379

      #- QUEUE_CONNECTION=sync

      #- MEMCACHED_HOST=127.0.0.1
      #- AWS_ACCESS_KEY_ID=1trAFuitOXDiG6ly8Ek4
      #- AWS_SECRET_ACCESS_KEY=wDUt43w1qLA12T8VZdIKXiSySJCLpRAn5uwsa8xY
      #- AWS_DEFAULT_REGION=us-east-1
      #- AWS_BUCKET=krayincrm
      #- BROADCAST_DRIVER=log

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.krayincrm321a1a2.rule=Host(`crm.domussimob.com.br`) && PathPrefix(`/`) ## Url do Krayin
        - traefik.http.services.krayincrm321a1a2.loadbalancer.server.port=80
        - traefik.http.routers.krayincrm321a1a2.service=krayincrm321a1a2
        - traefik.http.routers.krayincrm321a1a2.tls.certresolver=letsencryptresolver
        - traefik.http.routers.krayincrm321a1a2.entrypoints=websecure
        - traefik.http.routers.krayincrm321a1a2.tls=true


volumes:
  krayincrm321a1a2-data:
    external: true
    name: krayincrm321a1a2-data


networks: 
  externa: 
    external: true
  interna: 
    external: true


