
version: "3.7"

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_PASSWORD=gCrjaY7VbR9MJh49
    command: >
      postgres -c max_connections=1000
    networks: 
      - interna
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          #- node.hostname == worker1
      resources:
       limits:
         cpus: "2"
         memory: 2048M

volumes:
  postgres_data:
    external: true
    name: postgres_data

networks: 
  interna: 
    external: true



