
version: "3.7"
services:
  typebotc705c76-builder:
    image: baptistearno/typebot-builder:3.8
    networks: 
    - externa
    - interna
    environment:
    - POSTGRESDB_DATABASE=typebotc705c76
    - POSTGRESDB_HOST=postgres
    - POSTGRESDB_PORT=5432
    - POSTGRESDB_USER=postgres
    - POSTGRESDB_PASSWORD=gCrjaY7VbR9MJh49
    - ENCRYPTION_SECRET=1d7a58aba392d1beced0538df91ce0ce
    - DATABASE_URL=postgresql://postgres:gCrjaY7VbR9MJh49@postgres:5432/typebotc705c76
    - NEXTAUTH_URL=https://adminchat.domussimob.com.br
    - NEXT_PUBLIC_VIEWER_URL=https://chat.domussimob.com.br
    - ADMIN_EMAIL=francisbreit@gmail.com
    - DISABLE_SIGNUP=false
    - SMTP_AUTH_DISABLED=false
    - NEXTAUTH_URL_INTERNAL=http://localhost:3000
    - SMTP_USERNAME=9647e5001@smtp-brevo.com
    - SMTP_PASSWORD=JxHUhmVIEjyRBAT9
    - SMTP_HOST=smtp-relay.brevo.com
    - SMTP_PORT=587
    - NEXT_PUBLIC_SMTP_FROM='Domuus' <noreply@domussimob.com.br>
    - SMTP_SECURE=false
    #- GOOGLE_CLIENT_ID=
    #- GOOGLE_CLIENT_SECRET=
    - S3_ACCESS_KEY=4BGP2KZEHHAFUSYP4QAU
    - S3_SECRET_KEY=un+pw4h9O+mme86AZ6rLwG1NlZW+3bXTNTiCMiCB
    - S3_BUCKET=typebotc705c76
    - S3_ENDPOINT=s3.domussimob.com.br
    - S3_REGION=us-east-1  # Adicione esta linha
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.typebotc705c76-builder.rule=(Host(`adminchat.domussimob.com.br`))
      - traefik.http.routers.typebotc705c76-builder.entrypoints=websecure
      - traefik.http.routers.typebotc705c76-builder.priority=1
      - traefik.http.routers.typebotc705c76-builder.tls.certresolver=letsencryptresolver
      - traefik.http.routers.typebotc705c76-builder.service=typebotc705c76-builder
      - traefik.http.services.typebotc705c76-builder.loadbalancer.server.port=3000
      - traefik.http.services.typebotc705c76-builder.loadbalancer.passHostHeader=1
  typebotc705c76-viewer:
    image: baptistearno/typebot-viewer:3.8
    networks: 
    - externa
    - interna
    environment:
    - POSTGRESDB_DATABASE=typebotc705c76
    - POSTGRESDB_HOST=postgres
    - POSTGRESDB_PORT=5432
    - POSTGRESDB_USER=postgres
    - POSTGRESDB_PASSWORD=gCrjaY7VbR9MJh49
    - ENCRYPTION_SECRET=1d7a58aba392d1beced0538df91ce0ce
    - DATABASE_URL=postgresql://postgres:gCrjaY7VbR9MJh49@postgres:5432/typebotc705c76
    - NEXTAUTH_URL=https://adminchat.domussimob.com.br
    - NEXT_PUBLIC_VIEWER_URL=https://chat.domussimob.com.br
    - ADMIN_EMAIL=francisbreit@gmail.com
    - DISABLE_SIGNUP=false
    - SMTP_AUTH_DISABLED=false
    - NEXTAUTH_URL_INTERNAL=http://localhost:3000
    - SMTP_USERNAME=9647e5001@smtp-brevo.com
    - SMTP_PASSWORD=JxHUhmVIEjyRBAT9
    - SMTP_HOST=smtp-relay.brevo.com
    - SMTP_PORT=587
    - NEXT_PUBLIC_SMTP_FROM='Domuus' <noreply@domussimob.com.br>
    - SMTP_SECURE=false
    #- GOOGLE_CLIENT_ID=
    #- GOOGLE_CLIENT_SECRET=
    - S3_ACCESS_KEY=4BGP2KZEHHAFUSYP4QAU
    - S3_SECRET_KEY=un+pw4h9O+mme86AZ6rLwG1NlZW+3bXTNTiCMiCB
    - S3_BUCKET=typebotc705c76
    - S3_ENDPOINT=s3.domussimob.com.br
    - S3_REGION=us-east-1  # Adicione esta linha
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
      - traefik.enable=1
      - traefik.http.routers.typebotc705c76-viewer.rule=(Host(`chat.domussimob.com.br`))
      - traefik.http.routers.typebotc705c76-viewer.entrypoints=websecure
      - traefik.http.routers.typebotc705c76-viewer.priority=1
      - traefik.http.routers.typebotc705c76-viewer.tls.certresolver=letsencryptresolver
      - traefik.http.routers.typebotc705c76-viewer.service=typebotc705c76-viewer
      - traefik.http.services.typebotc705c76-viewer.loadbalancer.server.port=3000
      - traefik.http.services.typebotc705c76-viewer.loadbalancer.passHostHeader=1

networks: 
  externa: 
    external: true
  interna: 
    external: true


